site_name: Projects
site_url: https://projects.tightbytes.com
# edit_uri: 'http://127.0.0.1:8000/docs/'
theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode
      accent: pink
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - assets/css/custom.css

nav:
  - Home: index.md

  - Blogs:
    - blogs/index.md
    - Blog 2022: blogs/Blog22.md
    - Blog 2024: blogs/Blog24.md
    - Blog 2025: blogs/Blog25.md


  - Family:
    - family/index.md
    - Pappa's Account: family/pappa1.md

  - Music:
    - music/index.md
    - Harmony: music/Harmony.md
    - Sketches: music/Sketches.md
    - Transcriptions: music/Transcript.md
    - Violins: music/Violins.md

  - Other:
    - other/index.md
    - Foodie: other/Foodie.md
    - Garden21: other/Garden21.md
    - Garden22: other/Garden22.md
    - Garden25: other/Garden25.md
    - Health: other/Health.md
    - Matter: other/Matter.md

  - Tech:
    - tech/index.md
    - Browser: tech/browser.md
    - Linux: tech/Linux.md
    - Markdown: tech/Markdown.md
    - Miscellanae: tech/OStuff.md
    - Network: tech/Network.md
    - Python: tech/Python.md
    - Repair: tech/Repair.md

  - Visual Art:
    - visual/index.md
    - AI & Emily: visual/Emilyai.md
    - GIMP Tips: visual/GimpTips.md
    - Videos: visual/Videos.md
    - VScripts: visual/VScripts.md

plugins:
  - search
  - tags
  
validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.tightbytes.com/index.html
    - icon: fontawesome/brands/bluesky
      link: https://bluesky.com/robynsveil
