site_name: Projects
site_url: https://projects.tightbytes.com
edit_uri: 'http://127.0.0.1:8000/docs/'
use_directory_urls: true

validation:
  links:
    absolute_links: ignore

not_in_nav: |
  /includes/image-references.md

theme:
  name: material
  icon: assets/images/iconL.png
  logo: assets/images/logoL.png
  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: white
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/custom.css
  - stylesheets/extras.css

nav:
  - Home: index.md

  - Family:
      - family/index.md
      - Pappa's Account: family/pappa1.md
      - Translation Notes: family/pappa2.md

  - Other:
      - other/index.md
      - EVSolar: other/EVSolarProj.md
      - Foodie: other/Foodie.md
      - Garden21: other/Garden21.md
      - Garden22: other/Garden22.md
      - Garden25: other/Garden25.md
      - Health: other/Health.md
      - Refuse: other/Refusal.md

  - RCAS:
      - rcas/index.md
      - Docs v1b: rcas/BookingDoc.md
      - Exit Str: rcas/exitStrategy.md
      - Portal: rcas/Portal.md
      - Mar 24: rcas/rcas26-03-24.md
      - Mar 25: rcas/rcas26-03-25.md
      - Mar 27: rcas/rcas26-03-27.md
      - Mar 30: rcas/rcas26-03-30.md
      - Apr 01: rcas/rcas26-04-01.md
      - Apr 05: rcas/rcas26-04-05.md
      - Apr 06: rcas/rcas26-04-06.md
      - Apr 19: rcas/rcas26-04-19.md
      - May 05: rcas/rcas26-05-05.md
      - Aug 11: rcas/rcas26-08-11.md
      - FormPage: rcas/Formv01a.md
      - Code Base 1.1: rcas/Codev01a.md
      - Code Base 1.2: rcas/Codev01b.md
      - Code Base 1.3a: rcas/Codev01c.md
      - Code Base 1.3: rcas/Codev01ca.md
      - Code Base 1.4a: rcas/Codev01da.md
      - Code Base 1.4b: rcas/Codev01db.md
      - Code Base 1.4: rcas/Codev01dc.md
      - Code Base 1.5a: rcas/Codev01ea.md
      - Feature Requests: rcas/FeatureReq.md
      - Test Checklist: rcas/testChecklist.md

  - Tech:
      - tech/index.md
      - Browser: tech/browser.md
      - Docker: tech/docker.md
      - Docker-Restore: tech/docker-restore.md
      - Linux: tech/Linux.md
      - Markdown: tech/Markdown.md
      - Miscellanae: tech/OStuff.md
      - Network: tech/Network.md
      - Python: tech/Python.md
      - Repair: tech/Repair.md

plugins:
  - search
  - tags

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets:
     base_path:
        - docs
